---
- name: 'Fetch foreman ca certificate'
  shell: >
     hammer --fetch-ca-cert '{{ foreman_hammer_cli_config_host_url }}'

- name: 'Install the foreman ca certificate'
  shell: >
     install ~/.hammer/certs/foreman1.test.local_443.pem /etc/pki/ca-trust/source/anchors/

- name: 'Update the system-wide list of trusted CA certificates'
  shell: >
     update-ca-trust
